version: 2

jobs:
  build:
    docker:
      - image: milaudem/libgpuarray:0

    steps:
      - checkout
      - run:
        name: "Checkout Merge Commit"
        command: |
          if [[ -n "${CIRCLE_PR_NUMBER}" ]]
          then
              git fetch -u origin "+refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"
              git checkout -qf "pr/${CIRCLE_PR_NUMBER}/merge"
          fi
      - run:
        name: "Build Recipe"
        command: |
          export GPUARRAY_VERSION=`python -c 'import versioneer; print(versioneer.get_version())'`
          conda build --python 2.7 conda
          conda build --python 3.5 conda/pygpu
          conda build --python 3.6 conda/pygpu
      - run:
        name: "Upload Tagged Versions"
        command: |
          if [[ -n "${CIRCLE_TAG}" ]]
          then
              anaconda -t $BINSTAR_TOKEN upload --user=mila-udem /miniconda/conda-bld/linux-64/libgpuarray*
              anaconda -t $BINSTAR_TOKEN upload --user=mila-udem /miniconda/conda-bld/linux-64/pygpu*
          fi
       - store_artifacts:
         path: /miniconda/conda-bld/linux-64